// =============================================================================
// esbuild.server.js — bundle the custom production entry (src/server.ts) into
// build/server.js after `vite build`.
//
// The SvelteKit request handler (build/handler.js) and the runtime deps (ws,
// jose) are left external: `handler.js` is generated by adapter-node and sits
// next to the output; the deps live in node_modules. The realtime modules use
// relative imports, so no alias resolution is needed here.
// =============================================================================

import { build } from 'esbuild';

await build({
	entryPoints: ['src/server.ts'],
	outfile: 'build/server.js',
	bundle: true,
	platform: 'node',
	format: 'esm',
	target: 'node22',
	// `handler.js` is emitted by adapter-node; keep the import as-written so it
	// resolves to build/handler.js next to the output.
	external: ['./handler.js'],
	// Everything in node_modules (ws, jose, …) stays external at runtime.
	packages: 'external'
});

console.log('[poker] bundled build/server.js');
