apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jira-secrets
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: baseproject-vault
    kind: SecretStore
  data:
  - secretKey: JIRA_BASE_URL
    remoteRef:
      key: zon/v1/jira/estimation-station
      property: JIRA_BASE_URL
  - secretKey: JIRA_EMAIL
    remoteRef:
      key: zon/v1/jira/estimation-station
      property: JIRA_EMAIL
  - secretKey: JIRA_API_TOKEN
    remoteRef:
      key: zon/v1/jira/estimation-station
      property: JIRA_API_TOKEN
  - secretKey: JIRA_STORY_POINTS_FIELD
    remoteRef:
      key: zon/v1/jira/estimation-station
      property: JIRA_STORY_POINTS_FIELD
  