apiVersion: apps/v1
kind: Deployment
metadata:
  name: estimation-station
  labels:
    app: estimation-station
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: estimation-station
  template:
    metadata:
      labels:
        app: estimation-station
    spec:
      serviceAccountName: baseproject
      containers:
        - name: estimation-station
          image: quay.io/estimation-station/estimation-station:1.10.8-alpine
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "0.2"
              memory: 512Mi