---
name: Test frontend
on:
  workflow_call:
  workflow_dispatch:
  push:
    branches-ignore:
      - 'main'
    paths:
      - '.github/workflows/frontend-tests.yaml'
      - '.dockerignore'
      - 'Dockerfile'
      - 'frontend/**'
      - 'testing.yaml'
jobs:
  build:
    uses: zeitonline/gh-action-workflows/.github/workflows/build-test-push.yaml@e9d6b5018dbfd5b60023f76a5709be38da403f59 # 4.6.0
    with:
      service: frontend
      artifacts: build
