---
name: Test frontend
on:
  workflow_call:
  workflow_dispatch:
  push:
    branches-ignore:
      - 'main'
    paths:
      - '.github/workflows/frontend-tests.yaml'
      - '.dockerignore'
      - 'Dockerfile'
      - 'frontend/**'
      - 'testing.yaml'
jobs:
  build:
    uses: zeitonline/gh-action-workflows/.github/workflows/build-test-push.yaml@4b30983430304d849d8e86702555b29768d0c00e # 4.5.1
    with:
      service: frontend
      artifacts: build
