name: Check code issues
on:
  workflow_dispatch:
  push:
    branches-ignore:
      - 'main'
jobs:
  commitlint:
    uses: zeitonline/gh-action-workflows/.github/workflows/commit-lint.yaml@e9d6b5018dbfd5b60023f76a5709be38da403f59 # 4.6.0
  linter:
    uses: zeitonline/gh-action-workflows/.github/workflows/lefthook.yaml@e9d6b5018dbfd5b60023f76a5709be38da403f59 # 4.6.0
    with:
      node-version: "lts/*"
      setup-command: |
        uv tool install lefthook
        cd frontend/
        npm install
