name: Check code issues
on:
  workflow_dispatch:
  push:
    branches-ignore:
      - 'main'
jobs:
  commitlint:
    uses: zeitonline/gh-action-workflows/.github/workflows/commit-lint.yaml@4b30983430304d849d8e86702555b29768d0c00e # 4.5.1
  linter:
    uses: zeitonline/gh-action-workflows/.github/workflows/lefthook.yaml@4b30983430304d849d8e86702555b29768d0c00e # 4.5.1
    with:
      node-version: "lts/*"
      setup-command: |
        uv tool install lefthook
        cd frontend/
        npm install
